
name: Update Casebook Overview

on:
  push:
    branches:
      - main

jobs:
  update-cases:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install pyyaml

      - name: Update cases-overview and docs index
        run: |
          cd the-casebook
          python update_cases_overview.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add the-casebook/cases-overview.md the-casebook/docs/index.md
          git commit -m "chore: auto-update cases overview and docs index [skip ci]" || echo "No changes to commit"
          git push

  deploy-pages:
    needs: update-cases
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./the-casebook/docs

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
